# Which movies did Christopher Nolan direct?

PREFIX schema: <https://schema.org/>
PREFIX kg: <https://example.org/ontology/>

SELECT ?movie ?title
WHERE {
    <https://example.org/person/525> kg:directedMovie ?movie .
    ?movie schema:name ?title .
}
ORDER BY ?title