# Which country is "Avengers: Endgame" the movie's production company from?

PREFIX schema: <https://schema.org/>
PREFIX kg: <https://example.org/ontology/>

SELECT *
WHERE {
    <https://example.org/movie/299534> kg:productionCountry ?country .
    ?country schema:name ?name .
}
ORDER BY ?name
