# What do we know about Tom Holland other sources (DBpedia or Wikidata)?

PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT ?p ?o
WHERE {
    <https://example.org/person/1136406> owl:sameAs ?remote_entity .
    ?remote_entity ?p ?o .
}