# List 20 directors

PREFIX schema: <https://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT DISTINCT *
WHERE {
  ?movie_id a schema:Movie .
  ?movie_id schema:name ?movie_name .
  ?movie_id schema:director ?director_id .
  ?director_id schema:name ?director_name .
}
LIMIT 20