# List 5 actors for "Spider-Man: Brand New Day" the movie

PREFIX schema: <https://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT DISTINCT *
WHERE {
  ?movie_id a schema:Movie .
  ?movie_id schema:name ?movie_name .
  ?movie_id schema:actor ?actor_id .
  ?actor_id schema:name ?actor_name .
  FILTER (?movie_name = "Spider-Man: Brand New Day")
  FILTER (isIRI(?actor_id))
}
LIMIT 5