# What is the basic information of "The Odyssey" the movie?

PREFIX schema: <https://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?p ?o
WHERE {
    ?id a schema:Movie .
    ?id schema:name ?movie_name .
    ?id ?p ?o .
    FILTER (?movie_name = "The Odyssey")
}