# List 20 highest-rated "Action" movies since 2020

PREFIX schema: <https://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT DISTINCT ?movie_name ?genre ?date (?r AS ?rating_value) (?rc AS ?rating_count)
WHERE {
    ?id a schema:Movie .
    ?id schema:name ?movie_name .
    ?id schema:genre ?genre_id .
    ?genre_id schema:name ?genre .
    ?id schema:datePublished ?date .
    ?id schema:aggregateRating ?rating .
    ?rating schema:ratingValue ?r .
    ?rating schema:ratingCount ?rc .
    FILTER (?genre = "Action")
    FILTER (?date >= "2020-01-01"^^xsd:date)
}
ORDER BY DESC(?r)
LIMIT 20