# List 20 highest-rated "Action" movies since 2020 that starred Tom Holland

PREFIX schema: <https://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT DISTINCT ?movie_name ?genre ?date ?actor_name
WHERE {
    ?id a schema:Movie .
    ?id schema:name ?movie_name .
    ?id schema:datePublished ?date .
    ?id schema:genre ?g .
    ?g schema:name ?genre .
    ?id schema:actor ?a .
    ?a schema:actor ?actor_id .
    ?actor_id schema:name ?actor_name .
    FILTER (?genre = "Action")
    FILTER (?date >= "2020-01-01"^^xsd:date)
    FILTER (?actor_name = "Tom Holland")
}
LIMIT 20